version: '3.4'
services:
  app:
    image: train-docker/laravel:v2
    restart: unless-stopped
    volumes:
      - ./:/var/www/html

  webserver:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
